Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.hostname = "vagrant-node"
  config.vm.network "public_network",
    dev: "wlp4s0",
    mode: "bridge",
    ip: "192.168.1.220"

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.cpus = 2
    libvirt.memory = 2048

    libvirt.cpu_mode  = "custom"
    libvirt.cpu_model = "kvm64"
    libvirt.cpu_fallback = "allow"
  end
end

