apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp 
    type: front-end
spec:
  template:
     metadata:
       name: nginx
       labels:
         app: myapp
         type: front-end
     spec:
       containers:
       - name: nginx-continaer
         image: nginx
  replicas: 3
