apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zone-aware-daemon
  namespace: infra
spec:
  selector:
    matchLabels:
      app: zone-aware-daemon
  template:
    metadata:
      labels:
        app: zone-aware-daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: Exists
      containers:
        - name: busybox
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - printenv ZONE && sleep 3600
          env:
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['topology.kubernetes.io/zone']
