# Question 4 - DaemonSet: network-monitor
#
# Namespace: system
# Name: network-monitor
# Image: busybox:1.36
# Command: Monitor network information on each worker node
#
# Specifications:
# - Nodes: All nodes (excluding control-plane)
# - Environment Variables: NODE_IP from pod.status.podIP
# - Volumes: HostPath /var/log mounted at /var/log (DirectoryOrCreate)
# - Init Container: Create /var/log/network-info.log if it doesn't exist
# - Resources: Requests (CPU: 50m, Memory: 32Mi), Limits (CPU: 100m, Memory: 64Mi)
# - Scheduling: One Pod per worker node, skip control-plane nodes
#
# Task: Create a DaemonSet that monitors network information on each worker node and logs it periodically.
# Use an init container to ensure the log file exists, and verify that Pods do NOT run on control-plane nodes.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-monitor
  namespace: system
spec:
  selector:
    matchLabels:
      app: network-monitor
  template:
    metadata:
      labels:
        app: network-monitor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      initContainers:
        - name: init-log-file
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              [ ! -f /var/log/network-info.log ] && touch /var/log/network-info.log
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
      containers:
        - name: network-monitor
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              while true; do
                TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
                INTERFACE=$(ip addr show eth0 | grep 'inet ' | awk '{print $2}')
                GATEWAY=$(ip route | grep default | awk '{print $3}')
                echo "[TIMESTAMP] $TIMESTAMP [INTERFACE] eth0: $INTERFACE [GATEWAY] $GATEWAY" >> /var/log/network-info.log
                sleep 60
              done
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log
            type: DirectoryOrCreate
