apiVersion: v1
kind: Deployment 
metadata:
  name: webapp-green
  label:
    color: green 
spec:
  template:
    metadata:
      name: webapp-green-pod 
      label:
        color: green 
    spec:
      containers:
      - name: webapp 
        image: kodecloud/webapp-color:v1
        ports:
          - containerPort: 8080
  replicas: 3

  
