site_name: KillerCoda Notes
site_description: Preparation notes for CKA
site_author: Vikash Kumar

docs_dir: compose

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist
