name: 'Build MkDocs Site'
description: 'Build a MkDocs documentation site'

inputs:
  mkdocs-config:
    description: 'Path to mkdocs config'
    required: true
  output-folder:
    description: 'Output folder name'
    required: true
  requirements-file:
    description: 'Path to requirements.txt'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.x"

  - name: Cache pip
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles(inputs.requirements-file) }}

  - name: Install dependencies
    shell: bash
    run: |
      if [ -f "${{ inputs.requirements-file }}" ]; then
        pip install -r "${{ inputs.requirements-file }}"
      else
        pip install mkdocs mkdocs-material pymdown-extensions
      fi

  - name: Build site
    shell: bash
    run: |
      mkdocs build -f "${{ inputs.mkdocs-config }}" --site-dir "./_site/${{ inputs.output-folder }}"
      # Verify the build succeeded
      if [ ! -d "_site/${{ inputs.output-folder }}" ]; then
        echo "ERROR: _site/${{ inputs.output-folder }} directory not created"
        exit 1
      fi
      if [ ! -f "_site/${{ inputs.output-folder }}/index.html" ]; then
        echo "ERROR: index.html not found in _site/${{ inputs.output-folder }}"
        ls -la "_site/${{ inputs.output-folder }}" || echo "Directory listing failed"
        exit 1
      fi
      echo "✓ Build successful: _site/${{ inputs.output-folder }}/index.html exists"
