# base/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # Base64 encoded placeholder values
  DB_PASSWORD: cGxhY2Vob2xkZXI= # "placeholder"
  API_KEY: cGxhY2Vob2xkZXI= # "placeholder"
