apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod-v1
spec:
  containers:
    - name: nginx 
      image: nginx 
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "2Gi"
          cpu: 2
