# apiVersion: v1
# kind: Pod
# metadata:
#   name: ephemeral-file-pod
# spec:
#   containers:
#   - name: app
#     image: nginx
#     volumeMounts:
#     - name: share
#       mountPath: /mnt/share
#   volumes:
#   - name: share
#     csi:
#       driver: file.csi.azure.com
#       volumeAttributes:
#         protocol: smb
# ---
# # 1. Secret with Azure Storage credentials
# apiVersion: v1
# kind: Secret
# metadata:
#   name: azure-secret
# type: Opaque
# stringData:
#   azurestorageaccountname: <your-storage-account-name>
#   azurestorageaccountkey: <your-storage-account-key>
#
# ---
#
# # 2. Pod mounting existing Azure File share via CSI + secret
# apiVersion: v1
# kind: Pod
# metadata:
#   name: azure-csi-share-pod
# spec:
#   containers:
#   - name: app
#     image: nginx
#     volumeMounts:
#     - name: share
#       mountPath: /mnt/share
#   volumes:
#   - name: share
#     csi:
#       driver: file.csi.azure.com
#       readOnly: false
#       volumeAttributes:
#         shareName: myfileshare   # existing Azure File share
#         protocol: smb
#       nodePublishSecretRef:
#         name: azure-secret
#
# ---
#
# 3. Pod with ephemeral volume provisioned by Azure File CSI storage class
apiVersion: v1
kind: Pod
metadata:
  name: azure-csi-ephemeral-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: share
      mountPath: /mnt/share
  volumes:
  - name: share
    ephemeral:
      volumeClaimTemplate:
        metadata:
          labels:
            type: azurefile-ephemeral
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: azurefile-csi   # must exist in your cluster
          resources:
            requests:
              storage: 5Gi

