apiVersion: v1
kind: Pod
metadata:
  name: one
  labels:
    app: one
spec:
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - image: busybox
      name: one
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "hello worlds" >> /mnt/data/hello.txt
            sleep 10
          done
      volumeMounts:
        - name: shared
          mountPath: /mnt/data
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
      medium: Memory
