Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  
  config.vm.provider :libvirt do |lv|
    lv.cpus = 4
    lv.memory = 4056
  end

  config.vm.define "playground" do |pg|
    pg.vm.hostname = "playground"
  end
end
