apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: deepysvc
  name: deepysvc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deepy
  type: NodePort
status:
  loadBalancer: {}
