apiVersion: v1
kind: Pod
metadata:
  name: selector-demo
  labels:
    app: selector-app
spec:
  containers:
  - name: nginx
    image: nginx

  nodeSelector:
    size: small

  tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

