apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: vikash-dev-csr
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2RUQ0NBVjBDQVFBd01ERVRNQkVHQTFVRUF3d0tkbWxyWVhOb0xXUmxkakVaTUJjR0ExVUVDZ3dRWkdWMgpaV3h2Y0cxbGJuUXRkR1ZoYlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1ZrCkMwejN3K2J5ZTZMc1pHc0w4S2hkTlVPVkZoempJRnVGT0JwSzkyeGFwMU43VzlOVUMwbWozMERFVUVHZE1kbHYKUVdqbmNDdXlJL1FiUEZCdlJESGRLL2FEMzJQQm1TcUJ1cHJHYVVKbzF6bS8xSS9rQkdlSHhyYUJ4NzdCQ25zSwprTm1rM0dKc3hWcU0zZ0tyMnlNeUswVXlQMjAwZjFyWThCTWpUM2llNUc2N1FwYTByNnNEUzczVzRUOGhKUE9jCkhYNHNjMDlDYlg3bkYwWFE3ZkJtUUdVMmFNR21mQzdEYW5uamhsd0pUcndFUzRqa2t6aFAxZFM3RFhtU0pxL0wKbkcxeWdhSWRKcFczakRjUlVOdHdGYzdVVW5pQ2JBdHJkcHdsUVVTRXpMR28vYzBjL2YxK0JjY0gvTDFRbkNEcgpOY1NISi9NM2RiWExrbUsvUEhNQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBR2VBVFlQdlJLCnpGOC85UnplUVAyOHJhRDhucFhyTmNzc3JpUmp3VXVxencya3JualA1czlHZDQvMVlVamdrTHZoL3gvRklSTTcKRkl6aStPTTB3ZllhSGNnS2Fkd2h1cGlkeSt4U1IzaGdCeWVWSmIyNVk3a1dXdlhDQXh4TXhLbTBqck85M2M2MgpIWERZZEFrWDNxbGZHWEpzeFY0U0RtR1Q2MTY3dDBVbHZsRGNOWDdLL3pTMWV4SThCdThPMExaU2FzdzMvWW9mCnVRYkRJaXl3Z25NdGlzMGZSSURRb096YzcvZ0M0WkUxN2tOSWZQcFJEZ2x1WlJmVEFoUlJDWjhDNHdzVGJLWXMKOUgrMTlWNSt1cVMvbWRhYXk0VGxOcXhHekg3bXo2elJhWlVuRk5jWFczWXg1WmQxRVRLa2ZhcnBuRUk2MU1RcQpiM2p5TWV4VHRiVVcKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # 1 day
  usages:
  - client auth
  groups:
  - development-team
  - system:authenticated
  username: vikash-dev
