apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        command:
        - /bin/sh
        - -c
        - sleep 3600
        resources:
          requests:
            cpu: 30m
            memory: 30Mi
          limits:
            cpu: 200m
            memory: 100Mi
