apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dragon
  namespace: playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dragon
  template:
    metadata:
      labels:
        app: dragon 
    spec:
      containers:
        - name: dragon
          image: nginx
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service 
metadata:
  name: dragon-svc
  namespace: playground 
spec:
  selector:
    app: dragon
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
