apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: nginx
  namespace: playground
  name: deepy
spec:
  template:
    metadata:
      name: deepy-pod
      labels:
        app: nginx
      namespace: playground
    spec:
      containers:
        - name: deepy-contianer
          image: nginx
          ports:
            - name: http
              containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx
---

apiVersion: v1
kind: Service
metadata:
  name: deepy-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
