apiVersion: v1
kind: Service 
metadata:
  name: nginxdemos-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
  selector:
    app: nginxdemosapp
    tier: frontend
