apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deploy
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        practice: recreate
    spec:
      containers:
        - name: nginx-container
          image: nginx 
          ports:
            - containerPort: 80
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      practice: recreate
---
apiVersion: v1
kind: Service 
metadata:
  name: recreate-svc-01
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    practice: recreate
