apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      type: monitoring
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        type: monitoring
    spec:
      containers:
        - name: fluentd
          image: registry.k8s.io/fluentd-elasticsearch:1.20
      tolerations:
        - operator: "Exists"
