# =============================================================================
# NETWORK MODULE - COMPLEX TERRAGRUNT CONFIGURATION
# =============================================================================
# Foundation module - everything depends on this.
# Dependency Graph:
#   network (this) ─┬─► storage
#                   ├─► compute
#                   ├─► database
#                   └─► monitoring
# =============================================================================

include "root" {
  path = find_in_parent_folders("root.hcl")
}

# =============================================================================
# LOCAL VARIABLES - Complex calculations
# =============================================================================
locals {
  # Module identification
  module_name = "network"
  module_tier = "infrastructure"
  
  # Environment detection from path
  path_parts  = split("/", path_relative_to_include())
  region      = local.path_parts[1]
  environment = local.path_parts[2]
  
  # Environment-specific network CIDRs
  network_cidrs = {
    dev     = "10.0.0.0/16"
    staging = "10.1.0.0/16"
    prod    = "10.2.0.0/16"
  }
  
  # Subnet calculations
  vnet_cidr = local.network_cidrs[local.environment]
  subnets = {
    web  = cidrsubnet(local.vnet_cidr, 8, 0)
    app  = cidrsubnet(local.vnet_cidr, 7, 1)
    data = cidrsubnet(local.vnet_cidr, 8, 4)
    mgmt = cidrsubnet(local.vnet_cidr, 10, 20)
  }
  
  # Common tags
  common_tags = {
    Module      = local.module_name
    Region      = local.region
    Environment = local.environment
    ManagedBy   = "Terragrunt"
    Project     = "Azure-Complex-Demo"
    CostCenter  = local.environment == "prod" ? "PROD-001" : "DEV-001"
  }
  
  deploy_timestamp = formatdate("YYYY-MM-DD-hh-mm", timestamp())
}

# =============================================================================
# TERRAFORM SOURCE WITH HOOKS
# =============================================================================
terraform {
  source = "${get_parent_terragrunt_dir()}/modules//network"
  
  extra_arguments "common_vars" {
    commands = get_terraform_commands_that_need_vars()
  }
  
  extra_arguments "parallelism" {
    commands  = ["plan", "apply", "destroy"]
    arguments = ["-parallelism=20"]
  }
  
  # Pre-plan hook: Validate configuration
  before_hook "validate_config" {
    commands = ["plan", "apply"]
    execute  = ["echo", "🔍 Validating network configuration for ${local.environment}..."]
  }
  
  # Pre-apply hook: Show deployment info
  before_hook "show_deployment_info" {
    commands = ["apply"]
    execute  = ["echo", "🚀 Deploying network to ${local.region}/${local.environment}"]
  }
  
  # Post-apply hook: Success message (only runs on success)
  after_hook "deployment_success" {
    commands     = ["apply"]
    execute      = ["echo", "✅ Network deployment completed successfully!"]
    run_on_error = false
  }
  
  # Error hook: Alert on failure (commented - runs on both success/failure with run_on_error=true)
  # after_hook "deployment_failure" {
  #   commands     = ["apply", "plan"]
  #   execute      = ["echo", "❌ Network deployment failed! Check logs."]
  #   run_on_error = true
  # }
}

# =============================================================================
# GENERATE BLOCKS - Auto-generated files
# =============================================================================
generate "deployment_info" {
  path      = "_deployment_info.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    # Auto-generated by Terragrunt - DO NOT EDIT
    # Module: ${local.module_name}
    # Environment: ${local.environment}
    # Region: ${local.region}
    # Timestamp: ${local.deploy_timestamp}
  EOF
}

# =============================================================================
# INPUTS - Complex merged configuration
# =============================================================================
inputs = {
  # Project name (required by modules)
  project_name = "azure-complex-${local.environment}"
  
  # Resource naming
  resource_group_name = "rg-${local.environment}-${local.region}-network"
  vnet_name           = "vnet-${local.environment}-${local.region}"
  location            = local.region == "eastus" ? "East US" : "West Europe"
  
  # Network configuration
  address_space = [local.vnet_cidr]
  
  # Subnet configuration
  subnets = {
    "snet-web-${local.environment}" = {
      address_prefix    = local.subnets.web
      service_endpoints = ["Microsoft.Storage", "Microsoft.KeyVault"]
    }
    "snet-app-${local.environment}" = {
      address_prefix    = local.subnets.app
      service_endpoints = ["Microsoft.Storage", "Microsoft.Sql", "Microsoft.KeyVault"]
    }
    "snet-data-${local.environment}" = {
      address_prefix    = local.subnets.data
      service_endpoints = ["Microsoft.Sql", "Microsoft.Storage"]
    }
    "snet-mgmt-${local.environment}" = {
      address_prefix    = local.subnets.mgmt
      service_endpoints = ["Microsoft.KeyVault"]
    }
  }
  
  # NSG Rules - Environment specific
  nsg_rules = {
    web = {
      allow_http = {
        priority  = 100
        direction = "Inbound"
        protocol  = "Tcp"
        port      = 80
      }
      allow_https = {
        priority  = 110
        direction = "Inbound"
        protocol  = "Tcp"
        port      = 443
      }
    }
    app = {
      allow_internal = {
        priority  = 100
        direction = "Inbound"
        protocol  = "Tcp"
        port      = 8080
      }
    }
    data = {
      allow_sql = {
        priority  = 100
        direction = "Inbound"
        protocol  = "Tcp"
        port      = 1433
      }
    }
  }
  
  environment = local.environment
  tags        = merge(local.common_tags, { Layer = "Network" })
}
