apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-example
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/app-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc-example
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deploy-example
spec:
  selector:
    matchLabels:
      app: static-deploy-example
  template:
    metadata:
      name: static-pod-example
      labels:
        app: static-deploy-example
    spec:
      containers:
        - name: debugger
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "hello" > /data/index.html
              cat /data/index.html
              sleep 3600
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "16Mi"
              cpu: "50m"
          volumeMounts:
            - mountPath: /data
              name: app-storage
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: static-pvc-example
