apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - name: example-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    clientConfig:
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVYnU3b0tsdCtQOWtOYStIUUVWMzBNMndOdS9Zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qVXhNakk0Ck1UVXdOekF3V2hjTk16QXhNakkzTVRVd056QXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLNk1Uem0zCnpKS1JqbUUvTzRHWnh0eExmMEtrUUw5MU5RcDNqMUxHNWhoZlVVeXQrZ0daNzhlQnZvSkpsaUFuMlp5LzNsRFcKOWtjRlhwZ1VZcnZEaURQWEt1SGhVTllrNEFleTN3d2xHcWRYRUdBaU5mSk84Zmc4bGhLN0V6TGdLcUdldWpxKwpNME0rVGtVRy8rT1dhbWZVQlB1eWplR0F3SU4vcUNyVjJjallmOTZDaGp0OEJubEN5bWRlblFpdklwcTJFRkJlCkNhZW5EY1hRTGtkMVVwOVpFelh6YUlxdnRQY1Z4TGtQbDJWZUtwcmcwWVdKRGxLVHV1bktKVG5IamVHcWVVZzUKdmViVEMyUFNDaDB4am90NDZNajQraTg2MjdxTUl6MjJBWjZKcWJKNk1zdjdnQ2l4Q3h5ekovMGcxcHpKTnl1dAoxZklhaE1qNWRiZXRUTzhDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRk13T1M1bGhaSzBzTHhLcjNNbzFSM2ZHbWJzQU1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUFQMXVZeVVGU1RlL2J3bUFhWXZJTVM0TXhWM2FzNk85d3JMaEE1VnhBd3lONVV4cmtyTXIrNgo3eStvN1crY2N0dnd6UFBxUVJoUHVGOWN0OTQxaWsvOW1TK2l2KzFVRTdxZFZYbS9WY215MzlXSW1SVnVNY1c2Ckk0UXhpdzA0U0twVmZKZmhsQ1FYUnM5WTZpbzJXWlc1T2t3TDg2QU05b0dUd003TThBSVBwbmROaW1VU1ZNMTQKblNBbjMycXMvZ1JBaGN1S0ZWRDdKcnBGUmtJMWZzZU1QMVFtRWJockdteDlVOFk1UVdBTUIrbEFQTWJoeVFYbwppYjB6eHljQmtJQkVkNHdzeGhUaEVXV3g5WUVaK0hHYnhBVi8zREJCemVSZ0FRNkRRQVhkcWJKTVdQTkxaeGpQCjBJbGh3SG5PVHBDcXJjWnRDQlVJcHZSLzNtdkVoSWkvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]