apiVersion: v1
kind: Pod
metadata:
  name: random-name-generator
  namespace: debug
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh"]
      args:
        - -c
        - "while true; do shuf -i 0-100 -n 1 >> /opt/number.out; sleep 5; done"
      volumeMounts:
        - name: data-volume
          mountPath: /opt
  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: DirectoryOrCreate
  restartPolicy: Always

