Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |lv|
    lv.cpus = 2
    lv.memory = 2028
  end

  config.vm.define "linux1" do |lin1|
    lin1.vm.hostname = "linux1"
  end

  config.vm.define "linux2" do |lin2|
    lin2.vm.hostname = "linux2"
  end
end

