apiVersion: v1
kind: PersistentVolume
metadata:
  name: task3-pv 
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data
    type: DirectoryOrCreate
    
