{{ if .Values.traefik.forwardAuth }}
{{ if .Values.traefik.forwardAuth.address }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "microservice.fullname" . }}-forward-auth
spec:
  forwardAuth:
    {{ if .Values.traefik.forwardAuth.address }}
    address: {{ .Values.traefik.forwardAuth.address }}
    {{ end }}{{ if .Values.traefik.forwardAuth.skipTlsVerification | default true }}
    tls:
      insecureSkipVerify: true
    {{ end }}
{{- if .Values.traefik.v3.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "microservice.fullname" . }}-forward-auth
spec:
  forwardAuth:
    {{ if .Values.traefik.forwardAuth.address }}
    address: {{ .Values.traefik.forwardAuth.address }}
    {{ end }}{{ if .Values.traefik.forwardAuth.skipTlsVerification | default true }}
    tls:
      insecureSkipVerify: true
    {{ end }}
{{- end }}
{{ end }}
{{ end }}