apiVersion: v1
kind: Pod 
metadata:
  name: multipod
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
