apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-example
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - minikube-m02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc-example
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: static-pv-example 
  resources:
    requests:
      storage: 100Mi
